config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users do
    resource :profile
  end
  
  resources :media
  
  resources :contacts
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end

app/models/media.rb
class Media < ActiveRecord::Base
    
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :user_name, presence: true, uniqueness: true
    validates :contact_email, presence: true, uniqueness: true
    validates :description, presence: true
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    def home
        @contact = Contact.new
    end
    
    def create
      @contact = Contact.new(contact_params)
      
      if @contact.save
        name = params[:contact][:name]
        email = params[:contact][:email]
        body = params[:contact][:comments]
        
        ContactMailer.contact_email(name, email, body).deliver
        
        redirect_to root_path
      else
        redirect_to root_path
      end
    end
    
    private
    
      def contact_params
        params.require(:contact).permit(:name, :email, :comments)
      end
    
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
    def index
        
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        @contact = Contact.new
    end
    
    def create
      @contact = Contact.new(contact_params)
      
      if @contact.save
        name = params[:contact][:name]
        email = params[:contact][:email]
        body = params[:contact][:comments]
        
        ContactMailer.contact_email(name, email, body).deliver
        
        redirect_to root_path
      else
        redirect_to root_path
      end
    end
    
    private
    
      def contact_params
        params.require(:contact).permit(:name, :email, :comments)
      end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :only_current_user
    
    def new
        @user = User.find( params[:user_id] )
        @profile = Profile.new
    end
    
    def create
        @user = User.find( params[:user_id] )
        @profile = @user.build_profile(profile_params)
        if @profile.save
           redirect_to user_path( params[:user_id] ) 
        else
           render action: :new 
        end
    end
    
    def edit
      @user = User.find( params[:user_id] )
      @profile = @user.profile
    end
    
    def update 
      @user = User.find( params[:user_id] )
      @profile = @user.profile
      if @profile.update_attributes(profile_params)
        redirect_to user_path(params[:user_id] )
      else
        render action: :edit
      end
    end
    
    
    
   
   private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :user_name, :contact_email, :description, :avatar)
    end
    
    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def show
        @user = User.find ( params[:id] )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Disabled</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
</head>
<body>

  <%= yield %>


</body>
</html>

app/views/media/index.html.erb
<!DOCTYPE html>
<html>
<body>
  <%= link_to "Home page", root_path %>
  
  <div class="container text-center">
      <h1>News and Media</h1>
      <embed width="420" height="315"
      src="http://www.youtube.com/embed/V2xp-qtUlsQ">
  
  <hr />
  <h1>News and Updates!</h1>
  <p>We will be releasing a new update on Feb 25 2016!</p>
  
</div>  
</body>
</html>

app/views/profiles/edit.html.erb
<%= link_to "Home page", root_path %>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit your Profile</h1>
        <div class="well">
            <%= form_for @profile, url: user_profile_path, html: { multipart: true } do |f| %>
              <div class="form-group">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :contact_email %>
                <%= f.text_field :contact_email, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :description %>
                <%= f.text_area :description, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :avatar %>
                <%= f.file_field :avatar, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.submit "Update Profile", class: 'btn btn-primary' %>
              </div>
            <% end %>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
Form for user to create

app/views/users/show.html.erb
<%= link_to "Home page", root_path %>
<div class="container">
<div class="row">
    <div class="col-md-3 text-center">
      <%= image_tag @user.profile.avatar.url %>  
    </div>
    <div class="col-md-6">
        <h1><%= @user.profile.user_name %><br/></h1>
        <div class="well">
            <h3>Description</h3>
            <%= @user.profile.description %>
        </div>    
    </div>
</div>
</div>